spring:
  application:
    name: onlineshop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: helloworld
  thymeleaf:
    cache: false
    mode: HTML
server:
  port: 8080
  servlet:
    session:
      timeout: PT24H


mybatis:
  type-aliases-package: com.xlw.onlineshop.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true